### ISSUE TITLE
cudnn and CUDA out of mamory errors when running train.py

### ISSUE THREAD

**Issue by liuyiqing2018** [franciszchen/PTree-Net#4]
Hi Francis,

When I tried to run your code, I found a cudnn error like this when backpropagation:
`Variable._execution_engine.run_backward( RuntimeError: Unable to find a valid cuDNN algorithm to run convolution cuda version`

Then I disabled cudnn,
`torch.backends.cudnn.enabled = False `

and it ran through several WSIs and stopped at:

`_, features_bottom, _ = extractor_bottom(x=input_bottom) # bottom level`

because of the CUDA out of memory error. So I wonder what versions your cuda and cudnn are, and how shoud I set the configuration to avoid CUDA out of memory error? Thank you very much!

**Comment by franciszchen** [comment]
Thanks for your interest. I remember the CUDA should be 10.1, as the pytorch=1.5.0. The cudnn version should be compatible with these two versions. In fact, I haven't encountered such a problem, and I am afraid this is a hardware problem. For example, the experiments were performed on P40 (24GB) HPC with enough memory. Another potential cause may be that your input WSI is larger, which demands more resources under the same hyper-parameters.

**Comment by liuyiqing2018** [comment]
Thanks for your reply! I have found the bug and fixed it. The cudnn error was raised due to the incompatible of the CUDA version and my GPU. My GPU is GTX 3090, and the first CUDA version to recognize the RTX3090 is 11.1. So I updated my CUDA and other dependencies, and it works fine. BTW, I changed the feature extractors into squeezenet to reduce the graphic memory consumption.

**Comment by franciszchen** [comment]
Sounds great! Thanks again for your interest at this work :)
